import { Request, Response } from 'express'
import TerritoryService from '../libs/territory.service'

export const getCountries = async (req: Request, res: Response) => {

  const countries: string[] = [
    "France/DOM TOM",
    "Afghanistan",
    "Afrique du Sud",
    "Albanie",
    "Algérie",
    "Allemagne",
    "Andorre",
    "Angola",
    "Antigua-et-Barbuda",
    "Arabie Saoudite",
    "Argentine",
    "Arménie",
    "Aruba",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bahamas",
    "Bahreïn",
    "Bangladesh",
    "Barbade",
    "Belgique",
    "Belize",
    "Bermudes",
    "Bhoutan",
    "Birmanie",
    "Biélorussie",
    "Bolivie",
    "Bosnie-Herzégovine",
    "Botswana",
    "Brunei",
    "Brésil",
    "Bulgarie",
    "Burkina Faso",
    "Burundi",
    "Bénin",
    "Cambodge",
    "Cameroun",
    "Canada",
    "Cap Vert",
    "Chili",
    "Chine",
    "Chypre",
    "Colombie",
    "Comores",
    "Congo",
    "Congo (Rép. dém.)",
    "Corée du Nord",
    "Corée du Sud",
    "Costa Rica",
    "Croatie",
    "Cuba",
    "Curaçao",
    "Côte dIvoire",
    "Danemark",
    "Djibouti",
    "Dominique",
    "Egypte",
    "Emirats arabes unis",
    "Equateur",
    "Erythrée",
    "Espagne",
    "Estonie",
    "Eswatini",
    "Etats-Unis",
    "Ethiopie",
    "Fidji",
    "Finlande",
    "Gabon",
    "Gambie",
    "Ghana",
    "Gibraltar",
    "Grenade",
    "Groenland",
    "Grèce",
    "Guam",
    "Guatemala",
    "Guinée",
    "Guinée-Bissau",
    "Guinée-Équatoriale",
    "Guyana",
    "Géorgie",
    "Haïti",
    "Honduras",
    "Hong Kong (Chine)",
    "Hongrie",
    "Ile Maurice",
    "Inde",
    "Indonésie",
    "Irak",
    "Iran",
    "Irlande",
    "Islande",
    "Israël",
    "Italie",
    "Jamaïque",
    "Japon",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Kirghizistan",
    "Kiribati",
    "Kosovo",
    "Koweït",
    "Laos",
    "Lesotho",
    "Lettonie",
    "Liban",
    "Liberia",
    "Libye",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Macao (Chine)",
    "Macédoine du Nord",
    "Madagascar",
    "Malaisie",
    "Malawi",
    "Maldives",
    "Mali",
    "Malte",
    "Maroc",
    "Mauritanie",
    "Mexique",
    "Micronésie",
    "Moldavie",
    "Monaco",
    "Mongolie",
    "Monténégro",
    "Mozambique",
    "Namibie",
    "Nauru",
    "Nicaragua",
    "Niger",
    "Nigéria",
    "Norvège",
    "Nouvelle-Zélande",
    "Népal",
    "Oman",
    "Ouzbékistan",
    "Pakistan",
    "Palaos",
    "Panama",
    "Papouasie-Nouvelle-Guinée",
    "Paraguay",
    "Pays-Bas",
    "Philippines",
    "Pologne",
    "Porto Rico",
    "Portugal",
    "Pérou",
    "Qatar",
    "Québec",
    "Roumanie",
    "Royaume-Uni",
    "Russie",
    "Rwanda",
    "République centrafricaine",
    "République dominicaine",
    "République tchèque",
    "Saint Martin (partie néerlandaise)",
    "Saint-Christophe-et-Niévès",
    "Saint-Marin",
    "Saint-Martin (partie française)",
    "Saint-Vincent-et-les-Grenadines",
    "Sainte-Lucie",
    "Salvador",
    "Samoa",
    "Samoa américaines",
    "Sao Tomé-et-Principe",
    "Serbie",
    "Seychelles",
    "Sierra Leone",
    "Singapour",
    "Slovaquie",
    "Slovénie",
    "Somalie",
    "Soudan",
    "Soudan du Sud",
    "Sri Lanka",
    "Suisse",
    "Suriname",
    "Suède",
    "Syrie",
    "Sénégal",
    "Tadjikistan",
    "Tanzanie",
    "Taïwan",
    "Tchad",
    "Territoires palestiniens",
    "Thaïlande",
    "Timor oriental",
    "Togo",
    "Tonga",
    "Trinité et Tobago",
    "Tunisie",
    "Turkménistan",
    "Turquie",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Vanuatu",
    "Vatican",
    "Venezuela",
    "Viêt Nam",
    "Yémen",
    "Zambie",
    "Zimbabwe",
    "Île de Man",
    "Îles Caïmans",
    "Îles Féroé",
    "Îles Mariannes du Nord",
    "Îles Marshall",
    "Îles Salomon",
    "Îles Turques-et-Caïques",
    "Îles Vierges britanniques"
  ]

  return res.json(countries)
}

export const getMunicipalitiesByName = async (req: Request, res: Response) => {
  const { name } = req.validQuery
  const municipalities = await TerritoryService.getMunicipalitiesByName(name as string)
  return res.json(municipalities)
}
